project:
  type: website
  output-dir: docs

website:
  title: "Solcore Education"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: solar-cell-simulation/tutorials.qmd
      - text: "Solcore Workshop 2023"
        file: solcore-workshop/workshop2023.qmd

  sidebar:
    - title: "Home"
      style: "floating"
      background: light
      contents:
        - index.qmd

    - title: "Tutorials"
      contents:
        - solar-cell-simulation/tutorials.qmd
        - auto: solar-cell-simulation/notebooks/*.ipynb

    - title: "Solcore Workshop 2023"
      contents:
        - solcore-workshop/workshop2023.qmd
        - auto: solcore-workshop/notebooks/*.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true