project:
  type: website
  output-dir: docs

website:
  title: "Solcore Education"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: solar-cell-simulation/tutorials.qmd
      - text: "Solcore Workshop 2023"
        file: solcore-workshop/workshop2023.qmd

  sidebar:
    - title: "Home"
      style: "floating"
      background: light
      contents:
        - index.qmd

    - title: "Tutorials"
      contents:
        - solar-cell-simulation/tutorials.qmd
        - auto: solar-cell-simulation/notebooks/*.ipynb

    - title: "Solcore Workshop 2023"
      contents:
        - solcore-workshop/workshop2023.qmd
#        - auto: solcore-workshop/notebooks/*.ipynb
        - solcore-workshop/notebooks/2-Efficiency_limits.ipynb
        - solcore-workshop/notebooks/4-Spectral2.ipynb
        - solcore-workshop/notebooks/5a-simple_Si_cell.ipynb
        - solcore-workshop/notebooks/5b-simple_GaAs_cell.ipynb
        - solcore-workshop/notebooks/6a-TMM_introduction.ipynb
        - solcore-workshop/notebooks/6b-arc_optimization.ipynb
        - solcore-workshop/notebooks/7-InGaP_Si_planar.ipynb
        - solcore-workshop/notebooks/8-grating_pyramids_OPTOS.ipynb
        - solcore-workshop/notebooks/9a-GaInP_GaAs_Si_grating.ipynb
        - solcore-workshop/notebooks/9b-GaInP_GaAs_Si_pyramids.ipynb
        - solcore-workshop/notebooks/10-perovskite_Si_rt.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true