---
title: "Schedule"
---

|             | Day 1 (Wednesday 22/11)                                                     |             | Day 2 (Thursday 23/11)                                                                                                                           |             | Day 3 (Friday 24/11)                                                                 |
|-----        |------------                                                                 |-----       |------------                                                                                                                                       |-----        |------------                                                                                                                        |
| _Themes:_   | **Introduction, efficiency limits & fitting data**                          |             | **Junction models & planar optics**                                                                                                              |             | **Advanced light-trapping structures**                                                                                           |
| 1.00 - 1.30 | Introduction to computer modelling & Solcore                                | 1.00 - 1.30 | Introduction to different junction models                                                                                                        | 1.00 - 1.20 | Introduction to RayFlare & different optical methods  |
| 1.30 - 2.15 | [Limiting current & voltage models](notebooks/2-Efficiency_limits.ipynb)    | 1.30 - 2.00 | [Planar Si cell using depletion approximation junction](notebooks/5a-simple_Si_cell.ipynb)                                                                 | 1.20 - 2.00 | [Effect of diffraction grating (RCWA) and ray-tracing (RT) on a silicon wafer](notebooks/8-grating_pyramids_OPTOS.ipynb)                  |
| 2.15 - 2.45 | _Break_                                                                     | 2.00 - 2.45 | Introduction to the transfer-matrix method: [interference](notebooks/6a-TMM_introduction.ipynb) and [anti-reflection coatings](notebooks/6b-arc_optimization.ipynb)  | 2.00 - 2.30 | [GaInP/GaAs/Si triple-junction cell with rear diffraction grating](notebooks/9a-GaInP_GaAs_Si_grating.ipynb)                                                     |
| 2.45 - 3.30 | [Shockley-Queisser efficiency limit](notebooks/2-Efficiency_limits.ipynb)   | 2.45 - 3.15 | _Break_                                                                                                                                          | 2.30 - 3.00 | _Break_                                                                                                                               |
| 3.30 - 4.00 | [Changing irradiance spectra](notebooks/4-Spectral2.ipynb)                  | 3.00 - 3.45 | [Planar Si cell using drift-diffusion junction](notebooks/5b-Si_cell_PDD.ipynb)                                                                            | 3.00 - 3.45 | [Epoxy-bonded GaInP/GaAs//Si triple-junction cell with pyramidally textured silicon](notebooks/9b-GaInP_GaAs_Si_pyramids.ipynb) |
| 4.00 - 4.15 | _Break_                                                                     | 3.45 - 4.15 | _Break_                                                                                                                                          | 3.45 - 4.30 | [Perovskite on silicon tandem cell with pyramidcal texturing](notebooks/10-perovskite_Si_rt.ipynb)                                                           |
| 4.15 - 5.00 | [Two-diode model fits to experimental data](notebooks/3-IV_fitting.ipynb)    | 4.15 - 5.00 | [Optical model of a planar III-V on Si tandem cell](notebooks/7-InGaP_Si_planar.ipynb)                                                                     | 4.30 - 5.00 | Using the Katana HPC                                                                                                       |
